/**
 * Error code constants.
 * Every error in the library has a unique code for programmatic handling.
 */

export const ErrorCodes = {
  // Format detection
  FORMAT_DETECTION_FAILED: 'FORMAT_DETECTION_FAILED',
  UNSUPPORTED_FORMAT: 'UNSUPPORTED_FORMAT',

  // Codec errors
  CODEC_INIT_FAILED: 'CODEC_INIT_FAILED',
  CODEC_NOT_FOUND: 'CODEC_NOT_FOUND',
  DECODE_FAILED: 'DECODE_FAILED',
  HEIC_DECODE_FAILED: 'HEIC_DECODE_FAILED',
  AVIF_DECODE_FAILED: 'AVIF_DECODE_FAILED',

  // Worker errors
  WORKER_CRASHED: 'WORKER_CRASHED',
  WORKER_TIMEOUT: 'WORKER_TIMEOUT',
  WORKER_POOL_EXHAUSTED: 'WORKER_POOL_EXHAUSTED',

  // Network errors
  FETCH_FAILED: 'FETCH_FAILED',
  FETCH_TIMEOUT: 'FETCH_TIMEOUT',
  INCOMPLETE_BUFFER: 'INCOMPLETE_BUFFER',

  // Capability errors
  PROBE_TIMEOUT: 'PROBE_TIMEOUT',
  PROBE_FAILED: 'PROBE_FAILED',
  NATIVE_DECODE_FAILED: 'NATIVE_DECODE_FAILED',

  // General
  ABORTED: 'ABORTED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_INPUT: 'INVALID_INPUT',
  RENDER_FAILED: 'RENDER_FAILED',
  SSR_NOT_SUPPORTED: 'SSR_NOT_SUPPORTED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
